# Generated by Django 4.1.4 on 2023-07-23 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_view_custom_user', 'Can view custom User'), ('can_change_custom_user', 'Can change custom user')]},
        ),
    ]
