# Generated by Django 4.1.4 on 2023-07-23 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_is_admin_user_is_school_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_super_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_school_admin',
            field=models.BooleanField(default=True),
        ),
    ]
