# Generated by Django 4.1.4 on 2023-07-24 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_is_super_admin_alter_user_is_school_admin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
