# Generated by Django 4.2.4 on 2023-08-04 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_user_is_school_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='fullname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_school_admin',
            new_name='is_editor',
        ),
        migrations.RemoveField(
            model_name='user',
            name='logo',
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
