# Generated by Django 4.2.4 on 2023-08-09 08:31

import app.models
import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='logoimage/')),
                ('chairman', models.CharField(max_length=150)),
                ('ChiefEditor', models.CharField(max_length=150)),
                ('DepartmentRegistrationNo', models.CharField(max_length=150)),
                ('contactNo', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('facebookUrl', models.URLField(blank=True, null=True)),
                ('twitterUrl', models.URLField(blank=True, null=True)),
                ('youtubeUrl', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='HorizontalAds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='horizontalads/')),
                ('url', models.URLField()),
                ('positionNumber', models.CharField(choices=[('first', 'First'), ('second', 'Second'), ('third', 'Third'), ('fourth', 'Fourth'), ('fifth', 'Fifth'), ('six', 'Six')], max_length=150)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),

     

        migrations.CreateModel(
            name='MainCategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie_name', models.CharField(max_length=150)),
                ('main_ctg_slug', app.models.CustomAutoSlugField(default=None, editable=False, populate_from='categorie_name', unique=True)),
                ('icons', models.ImageField(upload_to='categorieIcons/')),
                ('ordering', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['ordering'],
            },
        ),
        migrations.CreateModel(
            name='VerticalAds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='verticalads/')),
                ('url', models.URLField()),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SubCategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategorie_name', models.CharField(max_length=150)),
                ('subctgslug', app.models.CustomAutoSlugField(default=None, editable=False, populate_from='subcategorie_name', unique=True)),
                ('ordering', models.PositiveIntegerField()),
                ('maincategorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorie', to='app.maincategorie')),
            ],
            options={
                'ordering': ['ordering'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='newsimage/')),
                ('discriptions', ckeditor.fields.RichTextField()),
                ('news_slug', app.models.CustomAutoSlugField(always_update=True, editable=False, populate_from='title', unique=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('trending', models.BooleanField(default=False)),
                ('feature', models.BooleanField(default=False)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mainCtg', to='app.maincategorie')),
                ('repoter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repoter', to=settings.AUTH_USER_MODEL)),
                ('subCategorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='subCtg', to='app.subcategorie')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
                'ordering': ['-id'],
            },
        ),
    ]
