# Generated by Django 4.2.4 on 2023-08-10 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_news_subcategorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horizontalads',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='verticalads',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
