# Generated by Django 4.2.4 on 2023-08-10 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_horizontalads_url_alter_verticalads_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='horizontalads',
            name='page',
            field=models.CharField(choices=[('home_page', 'Home Page'), ('news_details', 'News Detail')], default='home_page', max_length=150),
        ),
        migrations.AddField(
            model_name='verticalads',
            name='page',
            field=models.CharField(choices=[('home_page', 'Home Page'), ('news_details', 'News Detail')], default='home_page', max_length=150),
        ),
    ]
