# Generated by Django 4.2.4 on 2023-08-10 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_horizontalads_page_verticalads_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='horizontalads',
            name='name',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='verticalads',
            name='name',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
