# Generated by Django 4.2.4 on 2023-08-14 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_contactus_ourteam_privacypolicy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ourteam',
            old_name='discriptions',
            new_name='about_our_team',
        ),
    ]
