# Generated by Django 4.2.4 on 2023-08-28 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_contactus_title_ourteam_title_privacypolicy_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='highlight',
            field=models.BooleanField(default=False),
        ),
    ]
